Repository faycalBordjah/E-motion-Back, pull requests merged in 2019-10, with the labels that each got.

#43 Add travis file for continuous integration
  .travis.yml
  README.md
Labels: enhancement

#44 Add travis file for continuous integration
  README.md
Labels: bug

#50 Fix error on vehicle repository
  src/main/java/com/motus/emotion/repository/VehicleRepository.java
Labels: bug

#52 Finish the JWT authentication system
  src/main/java/com/motus/emotion/config/SecurityConfig.java
  src/main/java/com/motus/emotion/controller/HomeRestController.java
  src/main/java/com/motus/emotion/dto/AuthDto.java
  src/main/java/com/motus/emotion/dto/UserDto.java
  src/main/java/com/motus/emotion/exception/AlreadyExistException.java
  src/main/java/com/motus/emotion/exception/NotFoundException.java
  src/main/java/com/motus/emotion/model/User.java
  src/main/java/com/motus/emotion/model/Vehicle.java
  src/main/java/com/motus/emotion/repository/RoleRepository.java
  src/main/java/com/motus/emotion/security/UserPrincipal.java
  src/main/java/com/motus/emotion/security/jwt/JwtFilter.java
  src/main/java/com/motus/emotion/service/impl/AuthenticationServiceImpl.java
  src/main/java/com/motus/emotion/service/impl/UserServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/main/resources/migrations/schema.sql
Labels: enhancement

#54 Configure the DB on travis
  .travis.yml
Labels: enhancement

#56 Improve authentication
  src/main/java/com/motus/emotion/config/SecurityConfig.java
  src/main/java/com/motus/emotion/controller/UserController.java
  src/main/java/com/motus/emotion/controller/VehicleController.java
  src/main/java/com/motus/emotion/model/User.java
  src/main/java/com/motus/emotion/security/CustomUserDetailsService.java
  src/main/java/com/motus/emotion/security/jwt/JwtFilter.java
  src/main/java/com/motus/emotion/security/jwt/JwtProvider.java
  src/main/java/com/motus/emotion/service/impl/AuthenticationServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/data.sql
Labels: enhancement

#60 Add swagger documentation config
  pom.xml
  src/main/java/com/motus/emotion/EmotionApplication.java
  src/main/java/com/motus/emotion/config/SecurityConfig.java
  src/main/java/com/motus/emotion/config/SwaggerConfig.java
  src/main/java/com/motus/emotion/controller/HomeRestController.java
  src/main/java/com/motus/emotion/controller/VehicleController.java
  src/main/java/com/motus/emotion/controller/admin/RentalRestController.java
  src/main/java/com/motus/emotion/controller/admin/UsersRestController.java
  src/main/java/com/motus/emotion/controller/admin/VehiclesRestController.java
  src/main/java/com/motus/emotion/controller/user/LocationRestController.java
  src/main/java/com/motus/emotion/controller/user/UserRestController.java
  src/main/resources/application.properties
Labels: documentation, enhancement

#61 Add a mail service to the application based on Gmail smtp server
  pom.xml
  src/main/java/com/motus/emotion/config/MailConfig.java
  src/main/java/com/motus/emotion/model/Mail.java
  src/main/java/com/motus/emotion/service/MailService.java
  src/main/java/com/motus/emotion/service/impl/MailServiceImpl.java
  src/main/resources/application.properties
Labels: enhancement

#62 Add 2 DB profiles
  pom.xml
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
  src/main/resources/data-h2.sql
  src/main/resources/data-mysql.sql
  src/main/resources/data.sql
  src/main/resources/db/migrations/schema.sql
  src/main/resources/schema-h2.sql
  src/main/resources/schema-mysql.sql
Labels: enhancement

#63 make address as a table
  src/main/java/com/motus/emotion/dto/UserDto.java
  src/main/java/com/motus/emotion/model/Address.java
  src/main/java/com/motus/emotion/model/User.java
Labels: enhancement

#64 update data and schema files
  src/main/java/com/motus/emotion/model/Location.java
  src/main/resources/data-h2.sql
  src/main/resources/data-mysql.sql
  src/main/resources/db/migrations/schema.sql
  src/main/resources/schema-mysql.sql
  src/main/resources/schema.sql
Labels: enhancement

#66 Jeuxdonnée
  src/main/resources/data-h2.sql
Labels: enhancement

#70 Fix start_date
  src/main/java/com/motus/emotion/dto/UserDto.java
  src/main/java/com/motus/emotion/model/Location.java
  src/main/resources/data-h2.sql
  src/main/resources/schema.sql
Labels: bug

#69 fix insert
  src/main/java/com/motus/emotion/controller/admin/FileController.java
  src/main/java/com/motus/emotion/controller/admin/RentalRestController.java
  src/main/java/com/motus/emotion/controller/admin/UsersRestController.java
  src/main/java/com/motus/emotion/dto/FileDto.java
  src/main/java/com/motus/emotion/dto/LocationDto.java
  src/main/java/com/motus/emotion/dto/UserDto.java
  src/main/java/com/motus/emotion/model/Address.java
  src/main/java/com/motus/emotion/model/FileDB.java
  src/main/java/com/motus/emotion/model/Location.java
  src/main/java/com/motus/emotion/model/LocationStatus.java
  src/main/java/com/motus/emotion/model/User.java
  src/main/java/com/motus/emotion/repository/FileDBRepository.java
  src/main/java/com/motus/emotion/repository/UserRepository.java
  src/main/java/com/motus/emotion/service/FileService.java
  src/main/java/com/motus/emotion/service/LocationService.java
  src/main/java/com/motus/emotion/service/UserService.java
  src/main/java/com/motus/emotion/service/impl/FileServiceImpl.java
  src/main/java/com/motus/emotion/service/impl/LocationServiceImpl.java
  src/main/java/com/motus/emotion/service/impl/UserServiceImpl.java
  src/main/resources/data-h2.sql
  src/main/resources/schema.sql
Labels: enhancement

#71 refactor
  src/main/java/com/motus/emotion/controller/HomeRestController.java
  src/main/java/com/motus/emotion/controller/VehicleController.java
  src/main/java/com/motus/emotion/controller/admin/FileController.java
  src/main/java/com/motus/emotion/controller/admin/UsersRestController.java
  src/main/java/com/motus/emotion/controller/admin/VehiclesRestController.java
  src/main/java/com/motus/emotion/controller/user/LocationRestController.java
  src/main/java/com/motus/emotion/controller/user/UserRestController.java
Labels: enhancement

#73 Improvement dev
  src/main/java/com/motus/emotion/config/SecurityConfig.java
  src/main/java/com/motus/emotion/controller/admin/VehiclesRestController.java
  src/main/java/com/motus/emotion/controller/user/LocationRestController.java
  src/main/java/com/motus/emotion/controller/user/UserRestController.java
  src/main/java/com/motus/emotion/dto/UserDto.java
  src/main/java/com/motus/emotion/exception/ForbiddenExceptionEmo.java
  src/main/java/com/motus/emotion/model/Vehicle.java
  src/main/java/com/motus/emotion/model/VehicleType.java
  src/main/java/com/motus/emotion/security/jwt/JwtEntryPoint.java
  src/main/java/com/motus/emotion/service/UserService.java
  src/main/java/com/motus/emotion/service/impl/LocationServiceImpl.java
  src/main/java/com/motus/emotion/service/impl/UserServiceImpl.java
  src/main/resources/data-h2.sql
Labels: enhancement

#74 Add a tag description to swagger doc (deprecated but I can not find o…
  src/main/java/com/motus/emotion/controller/HomeRestController.java
  src/main/java/com/motus/emotion/controller/VehicleController.java
  src/main/java/com/motus/emotion/controller/admin/FileController.java
  src/main/java/com/motus/emotion/controller/admin/RentalRestController.java
  src/main/java/com/motus/emotion/controller/admin/UsersRestController.java
  src/main/java/com/motus/emotion/controller/admin/VehiclesRestController.java
  src/main/java/com/motus/emotion/controller/user/LocationRestController.java
  src/main/java/com/motus/emotion/controller/user/UserRestController.java
Labels: documentation

#75 improve rest vehicle rest services
  src/main/java/com/motus/emotion/controller/VehicleController.java
  src/main/java/com/motus/emotion/model/VehicleType.java
  src/main/java/com/motus/emotion/repository/VehicleRepository.java
  src/main/java/com/motus/emotion/service/VehicleService.java
  src/main/java/com/motus/emotion/service/impl/VehicleServiceImpl.java
Labels: enhancement

#76 Improve last
  src/main/java/com/motus/emotion/controller/HomeRestController.java
  src/main/java/com/motus/emotion/controller/user/LocationRestController.java
  src/main/java/com/motus/emotion/model/Address.java
  src/main/java/com/motus/emotion/model/Vehicle.java
  src/main/java/com/motus/emotion/repository/AddressRepository.java
  src/main/resources/application-dev.properties
  src/main/resources/data-h2.sql
  src/main/resources/draft.sql
Labels: enhancement
